package pack;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddLottery.java
 *
 * Created on Sep 15, 2012, 3:13:00 PM
 */

/**
 *
 * @author shyam
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.AWTEventListener.*;
import java.util.*;
public class AddLottery extends javax.swing.JInternalFrame {

    /** Creates new form AddLottery */
    JFrame mainframe;
    public AddLottery(JFrame mainframe) {
        super("Add New Committee",true,true,true,true);
        this.mainframe=mainframe;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        bt_add = new javax.swing.JButton();
        bt_close = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tf_recurring = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_date = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_month = new javax.swing.JTextField();
        bt_date = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tf_nonrecurring = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add New Committee");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel2.setText("Enter Committee Name :");

        tf_name.setFont(new java.awt.Font("Tahoma", 0, 16));
        tf_name.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nameActionPerformed(evt);
            }
        });

        bt_add.setText("Add");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        bt_close.setText("Close");
        bt_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_closeActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel4.setText("Monthly Recurring :");

        tf_recurring.setFont(new java.awt.Font("Tahoma", 0, 16));
        tf_recurring.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_recurring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_recurringActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel5.setText("Committee  Date :");

        tf_date.setEditable(false);
        tf_date.setFont(new java.awt.Font("Tahoma", 0, 16));
        tf_date.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_dateActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel6.setText("Total Month :");

        tf_month.setFont(new java.awt.Font("Tahoma", 0, 16));
        tf_month.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_monthActionPerformed(evt);
            }
        });

        bt_date.setText("...");
        bt_date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_dateActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 16));
        jLabel7.setText("Non-Recurring :");

        tf_nonrecurring.setFont(new java.awt.Font("Tahoma", 0, 16));
        tf_nonrecurring.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_nonrecurring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_nonrecurringActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tf_nonrecurring, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_recurring, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_date, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_month, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(132, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_close, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_date, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(tf_month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_recurring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tf_nonrecurring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_add)
                    .addComponent(bt_close))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nameActionPerformed

    private void bt_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_closeActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_bt_closeActionPerformed

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        // TODO add your handling code here:
        Dbcon db=new Dbcon();
        db.connect();
        if(tf_name.getText().equals(""))
        {
            JOptionPane.showMessageDialog(mainframe,"Enter Committee Name ","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(tf_date.getText().equals(""))
        {
            JOptionPane.showMessageDialog(mainframe,"Select Date ","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(tf_month.getText().equals(""))
        {
            JOptionPane.showMessageDialog(mainframe,"Enter Month ","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(tf_recurring.getText().equals(""))
        {
            JOptionPane.showMessageDialog(mainframe,"Enter Recurring Amount","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(tf_nonrecurring.getText().equals(""))
        {
            JOptionPane.showMessageDialog(mainframe,"Enter Non-Recurring","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }        
        int t1=0;
        try
        {
            t1=1;
            int i1=Integer.valueOf(tf_month.getText());
            t1=2;
            int i2=Integer.valueOf(tf_recurring.getText());
            t1=3;
            int i3=Integer.valueOf(tf_nonrecurring.getText());
            t1=4;

            db.stmt.executeUpdate("insert into lottery(lottery_no,date,month,recurring,nonrecurring,status) values('"+tf_name.getText()+"','"+DateConverter.toYYYYMMDD(tf_date.getText())+"',"+tf_month.getText()+","+tf_recurring.getText()+","+tf_nonrecurring.getText()+",1)");
            db.stmt.executeUpdate("insert into investoraccount(lottery_no,investor_no,date,status) values('"+tf_name.getText()+"',1000,'"+DateConverter.toYYYYMMDD(tf_date.getText())+"',1)");
            db.stmt.executeUpdate("insert into borrower(lottery_no,br_no,name,date,status) values('"+tf_name.getText()+"',2000,'2000-"+tf_name.getText()+"','"+DateConverter.toYYYYMMDD(tf_date.getText())+"',1)");
            db.rslt=db.stmt.executeQuery("select investor_id from investoraccount where lottery_no='"+tf_name.getText()+"' and investor_no=1000");

            int invid=1000;
            while(db.rslt.next())
            {
                invid=Integer.valueOf(db.rslt.getString(1));
            }
            db.stmt.executeUpdate("insert into investorinfo(investor_id,name,f_name,address,contact_no,status) values("+invid+",'"+tf_name.getText()+"-Non-Recurring','Non-Recurring','--','--',1)");

            db.conn.commit();
            JOptionPane.showMessageDialog(mainframe,"Lottry IS Added!");
            tf_name.setText("");
            tf_date.setText("");
            tf_month.setText("");
            tf_recurring.setText("");
            tf_nonrecurring.setText("");

            // tf_name.setText("");
//            tf_description.setText("");
            db.disconnect();
        }
        catch(Exception e){
            db.disconnect();
            if(t1==1)
            {
                JOptionPane.showMessageDialog(mainframe,"Enter Lottery Month In Numeric !","Error",JOptionPane.ERROR_MESSAGE);System.out.println(e);
                return;
            }
            else if(t1==2)
            {
                JOptionPane.showMessageDialog(mainframe,"Enter Lottery Recurring In Numeric !","Error",JOptionPane.ERROR_MESSAGE);System.out.println(e);
                return;
            }

            else if(t1==3)
            {
                JOptionPane.showMessageDialog(mainframe,"Enter Lottery Non-Recurring In Numeric !","Error",JOptionPane.ERROR_MESSAGE);System.out.println(e);
                return;
            }
            else
            {
                JOptionPane.showMessageDialog(mainframe,"Lottry  Already Exists !","Error",JOptionPane.ERROR_MESSAGE);System.out.println(e);
                return;
            }
        }
        
    }//GEN-LAST:event_bt_addActionPerformed

    private void tf_recurringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_recurringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_recurringActionPerformed

    private void tf_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_dateActionPerformed

    private void tf_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_monthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_monthActionPerformed

    private void bt_dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_dateActionPerformed
        // TODO add your handling code here:
       tf_date.setText(DateConverter.toDDMMYYYY(new DatePicker(mainframe).setPickedDate()));
    }//GEN-LAST:event_bt_dateActionPerformed

    private void tf_nonrecurringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_nonrecurringActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_nonrecurringActionPerformed

    /**
    * @param args the command line arguments
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_close;
    private javax.swing.JButton bt_date;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tf_date;
    private javax.swing.JTextField tf_month;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_nonrecurring;
    private javax.swing.JTextField tf_recurring;
    // End of variables declaration//GEN-END:variables

}
