package pack;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DeleteMemberAccount.java
 *
 * Created on Nov 12, 2012, 3:02:18 PM
 */

/**
 *
 * @author shyam
 */

import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;
public class DeleteMemberAccount extends javax.swing.JInternalFrame {

    /** Creates new form DeleteMemberAccount */
    JFrame mainframe;
    Vector member_id=new Vector();
    public DeleteMemberAccount(JFrame mainframe) {
        super("Delete Member Account",true,true,true,true);
        this.mainframe=mainframe;
        initComponents();
         Dbcon db=new Dbcon();
        db.connect();
        try {
            String date="";
            db.rslt=db.stmt.executeQuery("select date from memberaccount where lottery_no='"+lottery.elementAt(c_lottery.getSelectedIndex())+"' && status=1");
            while(db.rslt.next())
            {
                date=db.rslt.getString(1);
            }
            l_date.setText("Date : "+DateConverter.toDDMMYYYY(date));
            db.rslt=db.stmt.executeQuery("select ac.member_id,ac.member_no,info.name,info.f_name,ac.person from memberaccount ac,memberinfo info where ac.member_id=info.member_id  && ac.date='"+date+"' &&lottery_no='"+lottery.elementAt(c_lottery.getSelectedIndex())+"' && ac.status=1");
            db.rslt.afterLast();
            int count=0,c1=0;
            if (db.rslt.previous())count=db.rslt.getRow();
            String data[][]=new String[1][5];
            db.rslt.beforeFirst();
            c1=count;
            count=0;
            member_id.clear();
            while(db.rslt.next()) {
                if(c1==count+1)
                {
                    member_id.addElement(db.rslt.getString(1));
                    data[0][0]=""+(1);
                    data[0][1]=db.rslt.getString(2);
                    data[0][2]=db.rslt.getString(3);
                    data[0][3]=db.rslt.getString(4);
                    data[0][4]=db.rslt.getString(5);
                }
                count++;
            }
            String header[]={"S.No","Member ID","Name","Father's Name","Person"};
            DefaultTableModel model=new DefaultTableModel(data,header);
            table.setModel(model);
            table.updateUI();
        } catch(Exception e){JOptionPane.showMessageDialog(mainframe,"Error"+e);}
        db.disconnect();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Dbcon db=new Dbcon();
        db.connect();
        try
        {
            db.rslt=db.stmt.executeQuery("select lottery_no from lottery where status=1");
            while(db.rslt.next())
            {
                lottery.addElement(db.rslt.getString(1));

                //l_ldate.setText();
            }

        }
        catch(Exception e){JOptionPane.showMessageDialog(mainframe,"Error"+e);}
        db.disconnect();
        c_lottery = new javax.swing.JComboBox();
        l_date = new javax.swing.JLabel();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Close");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delete Member Accounts");

        c_lottery.setModel(new javax.swing.DefaultComboBoxModel(lottery.toArray()));
        c_lottery.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c_lotteryItemStateChanged(evt);
            }
        });

        l_date.setText("Date :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jButton1)
                .addGap(35, 35, 35)
                .addComponent(jButton2)
                .addContainerGap(295, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(c_lottery, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(l_date, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_lottery, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(l_date, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Dbcon db=new Dbcon();
        db.connect();
        try {
            int reply = JOptionPane.showConfirmDialog(mainframe,
                                "Are You Sure Want TO Delete All Accounts ?",
                                "Delete" ,
                                JOptionPane.YES_NO_OPTION,
                                JOptionPane.WARNING_MESSAGE);
                    System.out.println(reply);
                        if (reply == JOptionPane.YES_OPTION)
                        {

                        }
                         else
                             return;

            for(int i=0;i<member_id.size();i++)
            {

                db.stmt.executeUpdate("delete from nonrecurring where member_id="+member_id.elementAt(i));
                db.stmt.executeUpdate("delete from investsheet where member_id="+member_id.elementAt(i));
                db.stmt.executeUpdate("delete from memberaccount where member_id="+member_id.elementAt(i));
                db.stmt.executeUpdate("delete from memberinfo where member_id="+member_id.elementAt(i));
                db.stmt.executeUpdate("delete from sheet where member_id="+member_id.elementAt(i));
            }
            db.conn.commit();
            String date="";
            db.rslt=db.stmt.executeQuery("select date from memberaccount where lottery_no='"+lottery.elementAt(c_lottery.getSelectedIndex())+"' && status=1");
            while(db.rslt.next())
            {
                date=db.rslt.getString(1);
            }
            l_date.setText("Date : "+DateConverter.toDDMMYYYY(date));
            db.rslt=db.stmt.executeQuery("select ac.member_id,ac.member_no,info.name,info.f_name,ac.person from memberaccount ac,memberinfo info where ac.member_id=info.member_id  && ac.date='"+date+"' &&lottery_no='"+lottery.elementAt(c_lottery.getSelectedIndex())+"' && ac.status=1");
            db.rslt.afterLast();
            int count=0,c1=0;
            if (db.rslt.previous())count=db.rslt.getRow();
            String data[][]=new String[1][5];
            db.rslt.beforeFirst();
            c1=count;
            count=0;
            member_id.clear();
            while(db.rslt.next()) {
                if(c1==count+1)
                {
                    member_id.addElement(db.rslt.getString(1));
                    data[0][0]=""+(1);
                    data[0][1]=db.rslt.getString(2);
                    data[0][2]=db.rslt.getString(3);
                    data[0][3]=db.rslt.getString(4);
                    data[0][4]=db.rslt.getString(5);
                }
                count++;
            }

            String header[]={"S.No","Member ID","Name","Father's Name","Person"};
            DefaultTableModel model=new DefaultTableModel(data,header);
            table.setModel(model);
            table.updateUI();

        } catch(Exception e){JOptionPane.showMessageDialog(mainframe,"Error"+e);}
        db.disconnect();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void c_lotteryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c_lotteryItemStateChanged
        // TODO add your handling code here:
        Dbcon db=new Dbcon();
        db.connect();
        try {
            String date="";
            db.rslt=db.stmt.executeQuery("select date from memberaccount where lottery_no='"+lottery.elementAt(c_lottery.getSelectedIndex())+"' && status=1");
            while(db.rslt.next())
            {
                date=db.rslt.getString(1);                
            }
            l_date.setText("Date : "+DateConverter.toDDMMYYYY(date));
            db.rslt=db.stmt.executeQuery("select ac.member_id,ac.member_no,info.name,info.f_name,ac.person from memberaccount ac,memberinfo info where ac.member_id=info.member_id  && ac.date='"+date+"' &&lottery_no='"+lottery.elementAt(c_lottery.getSelectedIndex())+"' && ac.status=1");
            db.rslt.afterLast();
            int count=0,c1=0;
            if (db.rslt.previous())count=db.rslt.getRow();
            String data[][]=new String[1][5];
            db.rslt.beforeFirst();
            c1=count;
            count=0;
            member_id.clear();
            while(db.rslt.next()) {
                if(c1==count+1)
                {
                    member_id.addElement(db.rslt.getString(1));
                    data[0][0]=""+(1);
                    data[0][1]=db.rslt.getString(2);
                    data[0][2]=db.rslt.getString(3);
                    data[0][3]=db.rslt.getString(4);
                    data[0][4]=db.rslt.getString(5);
                }
                count++;
            }

            String header[]={"S.No","Member ID","Name","Father's Name","Person"};
            DefaultTableModel model=new DefaultTableModel(data,header);
            table.setModel(model);
            table.updateUI();

        } catch(Exception e){JOptionPane.showMessageDialog(mainframe,"Error"+e);}
        db.disconnect();
}//GEN-LAST:event_c_lotteryItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c_lottery;
    java.util.Vector lottery=new java.util.Vector();
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_date;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
