package pack;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LotteryInformation.java
 *
 * Created on Oct 11, 2012, 3:05:28 PM
 */

/**
 *
 * @author shyam
 */
import javax.swing.*;
import javax.swing.table.*;
import java.awt.*;
import java.awt.event.*;
import java.util.*;

public class LotteryInformation extends javax.swing.JInternalFrame {

    /** Creates new form LotteryInformation */
    JFrame mainframe;
    Vector recurring,nonrecurring,date,member_id,person,lmonth,member,investor;
    int tmonth=0,trecurring,tfine,tdebit,tcredit,tinterest,ttotal,tbalance;
    long totalavailable=0;
    int arr[]=null;

    public LotteryInformation(JFrame mainframe) {
        super("Member Account",true,true,true,true);
        this.mainframe=mainframe;
        recurring=new Vector();
        nonrecurring=new Vector();
        date=new Vector();
        member_id=new Vector();
        person=new Vector();
        member=new Vector();
        investor=new Vector();
        lmonth =new Vector();
        initComponents();
       
        Dbcon db=new Dbcon();
        db.connect();
        for(int i=0;i<lottery.size();i++)
        {
            try
            {
                db.rslt=db.stmt.executeQuery("Select count(member_no),sum(person) from memberaccount where lottery_no='"+lottery.elementAt(i)+"'");
                if(db.rslt.next())
                {
                    member.addElement(db.rslt.getString(1));
                    person.addElement(db.rslt.getString(2));
                }

            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        for(int i=0;i<lottery.size();i++)
        {
            try
            {
                db.rslt=db.stmt.executeQuery("Select count(investor_no) from investoraccount where lottery_no='"+lottery.elementAt(i)+"'");
                if(db.rslt.next())
                {
                    investor.addElement(db.rslt.getString(1));
                }

            }
            catch(Exception e)
            {
                System.out.println(e);
            }
        }
        db.disconnect();
        l_date.setText("Lottery Starting Date :  "+DateConverter.toDDMMYYYY((String)date.elementAt(c_lottery.getSelectedIndex())));
        l_month.setText("Total Months :  "+lmonth.elementAt(c_lottery.getSelectedIndex()));
        l_recurring.setText("Recurring Amount : "+recurring.elementAt(c_lottery.getSelectedIndex()));
        l_nonrecurring.setText("Non-Recurring Amount : "+nonrecurring.elementAt(c_lottery.getSelectedIndex()));
        l_member.setText("Total No Of Member :  "+member.elementAt(c_lottery.getSelectedIndex()));
        l_person.setText("Total No Of Person :  "+person.elementAt(c_lottery.getSelectedIndex()));
        l_investor.setText("Total No Of Investor : "+investor.elementAt(c_lottery.getSelectedIndex()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        Dbcon db=new Dbcon();
        db.connect();
        try
        {
            db.rslt=db.stmt.executeQuery("select lottery_no,recurring,nonrecurring,date,month from lottery order by date desc");
            while(db.rslt.next())
            {
                lottery.addElement(db.rslt.getString(1));
                recurring.addElement(db.rslt.getString(2));
                nonrecurring.addElement(db.rslt.getString(3));
                date.addElement(db.rslt.getString(4));
                lmonth.addElement(db.rslt.getString(5));
                //l_ldate.setText();
            }

        }
        catch(Exception e){JOptionPane.showMessageDialog(mainframe,"Error"+e);}
        db.disconnect();
        c_lottery = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        l_date = new javax.swing.JLabel();
        l_month = new javax.swing.JLabel();
        l_member = new javax.swing.JLabel();
        l_person = new javax.swing.JLabel();
        l_investor = new javax.swing.JLabel();
        l_recurring = new javax.swing.JLabel();
        l_nonrecurring = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lottery Information");

        c_lottery.setModel(new javax.swing.DefaultComboBoxModel(lottery.toArray()));
        c_lottery.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                c_lotteryItemStateChanged(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        l_date.setText("Lottery Date :");

        l_month.setText("Total Month :");

        l_member.setText("Total Member :");

        l_person.setText("Total Person :");

        l_investor.setText("Total Investor  :");

        l_recurring.setText("Recurring   :");

        l_nonrecurring.setText("Non-Recurring  :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(l_date, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_month, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_member, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_person, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_investor, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_recurring, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_nonrecurring, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(378, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(l_date, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_month, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l_member, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l_person, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l_investor, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l_recurring, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(l_nonrecurring, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(c_lottery, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c_lottery, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void c_lotteryItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_c_lotteryItemStateChanged
        // TODO add your handling code here:
        l_date.setText("Lottery Starting Date :  "+DateConverter.toDDMMYYYY((String)date.elementAt(c_lottery.getSelectedIndex())));
        l_month.setText("Total Months :  "+lmonth.elementAt(c_lottery.getSelectedIndex()));
        l_recurring.setText("Recurring Amount : "+recurring.elementAt(c_lottery.getSelectedIndex()));
        l_nonrecurring.setText("Non-Recurring Amount : "+nonrecurring.elementAt(c_lottery.getSelectedIndex()));
        l_member.setText("Total No Of Member :  "+member.elementAt(c_lottery.getSelectedIndex()));
        l_person.setText("Total No Of Person :  "+person.elementAt(c_lottery.getSelectedIndex()));
        l_investor.setText("Total No Of Investor : "+investor.elementAt(c_lottery.getSelectedIndex()));
}//GEN-LAST:event_c_lotteryItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox c_lottery;
    java.util.Vector lottery=new java.util.Vector();
    private javax.swing.JButton jButton1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l_date;
    private javax.swing.JLabel l_investor;
    private javax.swing.JLabel l_member;
    private javax.swing.JLabel l_month;
    private javax.swing.JLabel l_nonrecurring;
    private javax.swing.JLabel l_person;
    private javax.swing.JLabel l_recurring;
    // End of variables declaration//GEN-END:variables

}
